export const charactersIdsFromPlayersInfoTable = {
    0: "captainfalcon",
    1: "donkeykong",
    2: "fox",
    3: "mrgameandwatch",
    4: "kirby",
    5: "bowser",
    6: "link",
    7: "luigi",
    8: "mario",
    9: "marth",
    10: "mewtwo",
    11: "ness",
    12: "peach",
    13: "pikachu",
    14: "iceclimbers",
    15: "jigglypuff",
    16: "samus",
    17: "yoshi",
    18: "zelda",
    19: "shiek",
    20: "falco",
    21: "younglink",
    22: "drmario",
    23: "roy",
    24: "pichu",
    25: "ganondorf"
}

export const characterIdsFromCombosTable = {
    0: "mario",
    1: "fox",
    2: "captainfalcon",
    3: "donkeykong",
    4: "kirby",
    5: "bowser",
    6: "link",
    7: "shiek",
    8: "ness",
    9: "peach",
    10: "popo", 
    11: "nana",
    12: "pikachu",
    13: "samus",
    14: "yoshi",
    15: "jigglypuff",
    16: "mewtwo",
    17: "luigi",
    18: "marth",
    19: "zelda",
    20: "younglink",
    21: "drmario",
    22: "falco",
    23: "pichu",
    24: "mrgameandwatch",
    25: "ganondorf",
    26: "roy"
}

export const stageIds = {
    0: "Dummy",
    1: "TEST",
    2: "Fountain of Dreams",
    3: "Pokémon Stadium",
    4: "Princess Peach's Castle",
    5: "Kongo Jungle",
    6: "Brinstar",
    7: "Corneria",
    8: "Yoshi's Story",
    9: "Onett",
    10: "Mute City",
    11: "Rainbow Cruise",
    12: "Jungle Japes",
    13: "Great Bay",
    14: "Hyrule Temple",
    15: "Brinstar Depths",
    16: "Yoshi's Island",
    17: "Green Greens",
    18: "Fourside",
    19: "Mushroom Kingdom I",
    20: "Mushroom Kingdom II",
    22: "Venom",
    23: "Poké Floats",
    24: "Big Blue",
    25: "Icicle Mountain",
    26: "Icetop",
    27: "Flat Zone",
    28: "Dream Land N64",
    29: "Yoshi's Island N64",
    30: "Kongo Jungle N64",
    31: "Battlefield",
    32: "Final Destination"
};