const moveImages = {
    falco: {
        "2": "/gifs/falco_gifs/falcojab1.gif",
        "3": "/gifs/falco_gifs/falcojab2.gif",
        "4": "/gifs/falco_gifs/falcojab3.gif",
        "5": "/gifs/falco_gifs/falcojab3.gif",
        "6": "/gifs/falco_gifs/flacodashattack.gif",
        "7": "/gifs/falco_gifs/falcoforwardtilt.gif",
        "8": "/gifs/falco_gifs/falcouptilt.gif",
        "9": "/gifs/falco_gifs/falcodowntilt.gif",
        "10": "/gifs/falco_gifs/falcofsmash.gif",
        "11": "/gifs/falco_gifs/falcousmash.gif",
        "12": "/gifs/falco_gifs/falcodsmash.gif",
        "13": "/gifs/falco_gifs/falconair.gif",
        "14": "/gifs/falco_gifs/falcofair.gif",
        "15": "/gifs/falco_gifs/falcobackair.gif",
        "16": "/gifs/falco_gifs/falcoupair.gif",
        "17": "/gifs/falco_gifs/falcodair.gif",
        "18": "/gifs/falco_gifs/flacoairnb.gif",
        "19": "/gifs/falco_gifs/falcosideb.gif",
        "20": "/gifs/falco_gifs/firebird.gif",
        "21": "/gifs/falco_gifs/falco_shine.gif",
        "32": "Get Up Attack (From Back)",
        "51": "Get Up Attack (From Front)",
        "52": "Pummel",
        "53": "Forward Throw",
        "54": "Back Throw",
        "55": "Up Throw",
        "56": "Down Throw"
    },
    fox: {
        "2": "/gifs/fox_gifs/foxjab.gif",
        "3": "/gifs/fox_gifs/foxjab2.gif",
        "4": "/gifs/fox_gifs/foxjab3.gif",
        "5": "/gifs/fox_gifs/foxjab3.gif",
        "6": "/gifs/fox_gifs/foxdashattack.gif",
        "7": "/gifs/fox_gifs/foxftilt.gif",
        "8": "/gifs/fox_gifs/foxutilt.gif",
        "9": "/gifs/fox_gifs/foxdtilt.gif",
        "10": "/gifs/fox_gifs/foxfsmash.gif",
        "11": "/gifs/fox_gifs/foxupsmash.gif",
        "12": "/gifs/fox_gifs/foxdsmash.gif",
        "13": "/gifs/fox_gifs/foxnair.gif",
        "14": "/gifs/fox_gifs/foxfair.gif",
        "15": "/gifs/fox_gifs/foxbair.gif",
        "16": "/gifs/fox_gifs/foxupair.gif",
        "17": "/gifs/fox_gifs/foxdair.gif",
        "18": "/gifs/fox_gifs/foxblaster.gif",
        "19": "/gifs/fox_gifs/foxsideb.gif",
        "20": "/gifs/fox_gifs/firefox.gif",
        "21": "/gifs/fox_gifs/foxshine.gif",
        "32": "Get Up Attack (From Back)",
        "51": "Get Up Attack (From Front)",
        "52": "Pummel",
        "53": "Forward Throw",
        "54": "Back Throw",
        "55": "Up Throw",
        "56": "Down Throw"
    },
    marth: {
        "2": "/gifs/marth_gifs/marthjab.gif",
        "3": "/gifs/marth_gifs/marthjab2.gif",
        "4": "/gifs/marth_gifs/marthjab3.gif",
        "5": "/gifs/marth_gifs/marthjab3.gif",
        "6": "/gifs/marth_gifs/marthdashattack.gif",
        "7": "/gifs/marth_gifs/marthftilt.gif",
        "8": "/gifs/marth_gifs/marthutilt.gif",
        "9": "/gifs/marth_gifs/marthdtilt.gif",
        "10": "/gifs/marth_gifs/marthfsmash.gif",
        "11": "/gifs/marth_gifs/marthusmash.gif",
        "12": "/gifs/marth_gifs/marthdsmash.gif",
        "13": "/gifs/marth_gifs/marthnair.gif",
        "14": "/gifs/marth_gifs/marthfair.gif",
        "15": "/gifs/marth_gifs/marthbair.gif",
        "16": "/gifs/marth_gifs/marthuair.gif",
        "17": "/gifs/marth_gifs/marthdair.gif",
        "18": "/gifs/marth_gifs/marthneutralb.gif",
        "19": "/gifs/marth_gifs/marthsideb1.gif",
        "20": "/gifs/marth_gifs/marthupb.gif",
        "21": "/gifs/marth_gifs/marthdownb.gif",
        "32": "Get Up Attack (From Back)",
        "51": "Get Up Attack (From Front)",
        "52": "Pummel",
        "53": "Forward Throw",
        "54": "Back Throw",
        "55": "Up Throw",
        "56": "Down Throw"
    }
}

export default moveImages