const moveImages = {
    falco: {
        "2": "/gifs/falco_gifs/jab1.gif",
        "3": "/gifs/falco_gifs/jab2.gif",
        "4": "/gifs/falco_gifs/jab3.gif",
        "5": "/gifs/falco_gifs/jab3.gif",
        "6": "/gifs/falco_gifs/dattack.gif",
        "7": "/gifs/falco_gifs/ftilt.gif",
        "8": "/gifs/falco_gifs/utilt.gif",
        "9": "/gifs/falco_gifs/dtilt.gif",
        "10": "/gifs/falco_gifs/fsmash.gif",
        "11": "/gifs/falco_gifs/usmash.gif",
        "12": "/gifs/falco_gifs/dsmash.gif",
        "13": "/gifs/falco_gifs/nair.gif",
        "14": "/gifs/falco_gifs/fair.gif",
        "15": "/gifs/falco_gifs/bair.gif",
        "16": "/gifs/falco_gifs/uair.gif",
        "17": "/gifs/falco_gifs/dair.gif",
        "18": "/gifs/falco_gifs/a-neutralb.gif",
        "19": "/gifs/falco_gifs/sideb.gif",
        "20": "/gifs/falco_gifs/upb.gif",
        "21": "/gifs/falco_gifs/downb.gif",
        "32": "Get Up Attack (From Back)",
        "51": "Get Up Attack (From Front)",
        "52": "/pummel.png",
        "53": "/fthrow.png",
        "54": "/bthrow.png",
        "55": "/upthrow.png",
        "56": "/dthrow.png"
    },
    fox: {
        "2": "/gifs/fox_gifs/jab1.gif",
        "3": "/gifs/fox_gifs/jab2.gif",
        "4": "/gifs/fox_gifs/jab3.gif",
        "5": "/gifs/fox_gifs/jab3.gif",
        "6": "/gifs/fox_gifs/dattack.gif",
        "7": "/gifs/fox_gifs/ftilt.gif",
        "8": "/gifs/fox_gifs/utilt.gif",
        "9": "/gifs/fox_gifs/dtilt.gif",
        "10": "/gifs/fox_gifs/fsmash.gif",
        "11": "/gifs/fox_gifs/usmash.gif",
        "12": "/gifs/fox_gifs/dsmash.gif",
        "13": "/gifs/fox_gifs/nair.gif",
        "14": "/gifs/fox_gifs/fair.gif",
        "15": "/gifs/fox_gifs/bair.gif",
        "16": "/gifs/fox_gifs/uair.gif",
        "17": "/gifs/fox_gifs/dair.gif",
        "18": "/gifs/fox_gifs/a-neutralb.gif",
        "19": "/gifs/fox_gifs/sideb.gif",
        "20": "/gifs/fox_gifs/upb.gif",
        "21": "/gifs/fox_gifs/downb.gif",
        "32": "Get Up Attack (From Back)",
        "51": "Get Up Attack (From Front)",
        "52": "/pummel.png",
        "53": "/fthrow.png",
        "54": "/bthrow.png",
        "55": "/upthrow.png",
        "56": "/dthrow.png"
    },
    marth: {
        "2": "/gifs/marth_gifs/jab1.gif",
        "3": "/gifs/marth_gifs/jab2.gif",
        "4": "",
        "5": "",
        "6": "/gifs/marth_gifs/dattack.gif",
        "7": "/gifs/marth_gifs/ftilt.gif",
        "8": "/gifs/marth_gifs/utilt.gif",
        "9": "/gifs/marth_gifs/dtilt.gif",
        "10": "/gifs/marth_gifs/fsmash.gif",
        "11": "/gifs/marth_gifs/usmash.gif",
        "12": "/gifs/marth_gifs/dsmash.gif",
        "13": "/gifs/marth_gifs/nair.gif",
        "14": "/gifs/marth_gifs/fair.gif",
        "15": "/gifs/marth_gifs/bair.gif",
        "16": "/gifs/marth_gifs/uair.gif",
        "17": "/gifs/marth_gifs/dair.gif",
        "18": "/gifs/marth_gifs/neutralb.gif",
        "19": "/gifs/marth_gifs/sideb.gif",
        "20": "/gifs/marth_gifs/upb.gif",
        "21": "/gifs/marth_gifs/downb.gif",
        "32": "Get Up Attack (From Back)",
        "51": "Get Up Attack (From Front)",
        "52": "/pummel.png",
        "53": "/fthrow.png",
        "54": "/bthrow.png",
        "55": "/upthrow.png",
        "56": "/dthrow.png"
    }
}

export default moveImages