const moveImages = {
    falco: {
        "2": "/gifs/falcojab1.gif",
        "3": "/gifs/falcojab2.gif",
        "4": "/gifs/falcojab3.gif",
        "5": "/gifs/falcojab3.gif",
        "6": "/gifs/flacodashattack.gif",
        "7": "/gifs/falcoforwardtilt.gif",
        "8": "/gifs/falcouptilt.gif",
        "9": "/gifs/falcodowntilt.gif",
        "10": "/gifs/falcofsmash.gif",
        "11": "/gifs/falcousmash.gif",
        "12": "/gifs/falcodsmash.gif",
        "13": "/gifs/falconair.gif",
        "14": "/gifs/falcofair.gif",
        "15": "/gifs/falcobackair.gif",
        "16": "/gifs/falcoupair.gif",
        "17": "/gifs/falcodair.gif",
        "18": "/gifs/flacoairnb.gif",
        "19": "/gifs/falcosideb.gif",
        "20": "/gifs/firebird.gif",
        "21": "/gifs/falco_shine.gif",
        "32": "Get Up Attack (From Back)",
        "51": "Get Up Attack (From Front)",
        "52": "Pummel",
        "53": "Forward Throw",
        "54": "Back Throw",
        "55": "Up Throw",
        "56": "Down Throw"
    },
    fox: {
        "2": "/gifs/foxjab.gif",
        "3": "/gifs/foxjab2.gif",
        "4": "/gifs/foxjab3.gif",
        "5": "/gifs/foxjab3.gif",
        "6": "/gifs/foxdashattack.gif",
        "7": "/gifs/foxftilt.gif",
        "8": "/gifs/foxutilt.gif",
        "9": "/gifs/foxdtilt.gif",
        "10": "/gifs/foxfsmash.gif",
        "11": "/gifs/foxupsmash.gif",
        "12": "/gifs/foxdsmash.gif",
        "13": "/gifs/foxnair.gif",
        "14": "/gifs/foxfair.gif",
        "15": "/gifs/foxbair.gif",
        "16": "/gifs/foxupair.gif",
        "17": "/gifs/foxdair.gif",
        "18": "/gifs/foxblaster.gif",
        "19": "/gifs/foxsideb.gif",
        "20": "/gifs/firefox.gif",
        "21": "/gifs/foxshine.gif",
        "32": "Get Up Attack (From Back)",
        "51": "Get Up Attack (From Front)",
        "52": "Pummel",
        "53": "Forward Throw",
        "54": "Back Throw",
        "55": "Up Throw",
        "56": "Down Throw"
    }
}

export default moveImages